name: Push release to deploy branch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push

    steps:
      - name: git-checkout
        uses: actions/checkout@v4

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: install-frontend-dependencies
        run: npm install -g pnpm && pnpm install

      - name: build-frontend
        run: pnpm build

      - name: configure-deploy-directory
        run: |
          mkdir deploy

          # Copy PHP backend as root (including dotfiles like .htaccess)
          cp -r backend/. deploy/

          # Move built frontend assets into public/client
          mv dist deploy/public/client

      - name: push-to-deploy-branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          publish_branch: deploy
          force_orphan: true
          commit_message: "Build: ${{ github.sha }}"
